// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://navllnaqpptmjieqvhqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hdmxsbmFxcHB0bWppZXF2aHF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTg2NDksImV4cCI6MjA2NDU5NDY0OX0.jClIpsC9FM8ioZJ68EPKyR1D6NrJDUCigXo-YdeiFXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);